### ISSUE TITLE
Migraciones

### ISSUE THREAD

**Issue by santiagogil** [decyt-tdf/siep#11]
Implementar migraciones de bases de datos integradas en build tanto para schemas como para carga inicial.

Además de las ventajas conocidas, permite mantener versionados los datasets que componen el sistema (esrablecimientos, cajas curriculares, etc.).

**Comment by gpabloandres** [comment]
Usaremos el Plugin de Migrations de CakeDC atendiendo a las consideraciones que citan en el README de su repo ([Ver aquí](https://github.com/CakeDC/migrations)).

**Comment by gpabloandres** [comment]
Proposal of Workflow Git with a modified database for push request:

Once the database has been updated, execute: $ Console/cake Migrations.migration generate
 
Iniciar Workflow de Git.

Obs: The migrations plugin and the schema shell offer before and after callbacks. We can implement our custom logic there to trigger an external bash script via shell_exec() to backup our DB in the before callbacks ([Ver aquí](https://github.com/CakeDC/migrations/blob/master/Docs/Documentation/Migrations.md#callbacks)).

**Comment by santiagogil** [comment]
Sisi. Lo del backup como pre hook es imprescindible!
Lo más probable es que lo implementemos como un servicio que levanta una imágen con cliente mysql que esjecuta los comandos del backup.

**Comment by gpabloandres** [comment]
Best practice is it to make a DB backup before any new version is deployed, even when no migration is involved. An application should be deployed through some script or have at least some script that can be triggered to create a backup of the database before a migration is executed. No matter what program (Liquibase: http://www.liquibase.org/) or CakePHP plugin we use.

**Comment by gpabloandres** [comment]
Se integró el Plugin Migrations con una migración inicial por consola de cake en el Pull Request #48

**Comment by gpabloandres** [comment]
Para generar el SCHEMA correctamente, se agrega la sentencia -f al comando en la consola de Cake:
                                               
Vendor/bin/cake Migrations.migration generate -f

Así, se fuerza a que todas la tablas (inclusive las que no tienen un modelo asociado) figuren en el SCHEMA.

Luego para generar la ESTRUCTURA de la base de datos (BD) a partir del SCHEMA generado, el comando a ejecutar en la consola de Cake es: 

Vendor/bin/cake Migrations.migration run all

Ya con la estructura de base de datos generadas, se puebla la BD con importaciones por medio de SQL.

**Comment by santiagogil** [comment]
Queda resuelto en #69
