### ISSUE TITLE
Edicion en las Inscripciones

### ISSUE THREAD

**Issue by MaTiUs77** [decyt-tdf/siep#154]
Al elegir la seccion en modo edicion, no impacta correctamente en las matriculas.

La misma vista de edicion la usa Pases, verificar impacto en matriculas

**Comment by gpabloandres** [comment]
Ya está resuelto el impacto a matrículas cuando un alumno se cambia de sección.

Paso a revisar el mismo tema pero para los alumnos pero para gestionar Pase - Inscripción.
