### ISSUE TITLE
Tabla Dinámica Alumnos por Sección.

### ISSUE THREAD

**Issue by MaTiUs77** [decyt-tdf/siep#172]
Al seleccionar el centro,  hay que mostrar de forma dependiente los años, los cursos

Exportar datos a PDF o EXCEL

**Comment by gpabloandres** [comment]
Reutilizar lógica y código de "Alumnos por Sección".

**Comment by MaTiUs77** [comment]
#203

**Comment by MaTiUs77** [comment]
Pull request relacionado: #203
