### ISSUE TITLE
Exportacion a Excel

### ISSUE THREAD

**Issue by MaTiUs77** [decyt-tdf/siep#202]
La libreria https://packagist.org/packages/maraya/cake-php-excel podria resolver la exportacion a excel.
Es necesario instalar algunas liberias en el contenedor de php-fpm, solicita entre otras cosas la libreria GD para php.

Dejo en sus manos Santi y Marcos para que instalen via composer este componente, para continuar testeando la exportacion a excel.

**Comment by santiagogil** [comment]
Meta. Mañana tempranito tiramos un build y lo probamos.
