### ISSUE TITLE
Constancia de Alumno Regular

### ISSUE THREAD

**Issue by gpabloandres** [decyt-tdf/siep#300]
En el cuadro de OPCIONES del VIEW de ALUMNOS se Habilitará el botón "CONSTANCIA DE ALUMNO REGULAR" para este tipo de impresión: [VER MODELO DE CONSTANCIA](https://drive.google.com/file/d/1zjTfvqMgYKMGT_HLs2sQY3x0xphDfNzz/view?usp=sharing)

**Comment by MaTiUs77** [comment]
Implementado en #310

**Comment by gpabloandres** [comment]
Modificar donde dice:
"...de ser presentada ante las autoridades educativas que correspondan..."
debe decir:
"...de ser presentada ante quien corresponda..."

**Comment by gpabloandres** [comment]
Verificar la impresión con múltiples cursos después de la resolución del Issue #328
