### ISSUE TITLE
Docker swarm

### ISSUE THREAD

**Issue by santiagogil** [decyt-tdf/siep#5]
No exactamente referente a modificaciones en el código de este repositorio, pero si precondición para otros issues.

**Comment by santiagogil** [comment]
Dado que ya contamos con servicios en producción, implementados sobre docker engine, no compatibles con docker swarm; resulta necesario:

* Implementar una segunda máquina virtual sobre vmware.
* Instalar y configurar swarm sobre esa VM.
* Migrar los servicios preexistentes a swarm (es una tarea sensilla en relación al beneficio que aporta. Unas pocas horas de desarrollo).
* Remplazar docker engine por docker swarm en la VM preexistente y unirla al cluster.

Esto nos permite:

* Implementar siep sobre una plataforma robusta y escalable.
* Favorecer a los servicios preexistentes al mejorar su infraestructura.
* Omogeneizar operaciones.
* Contar con una infraestructura que puede extenderse o migrarse más allá de los límites del datacenter (otra locación, servicios de cloud, etc.).

**Comment by gpabloandres** [comment]
Mi versión de Docker es: 17.03

**Comment by pablodeleon** [comment]
versión actual:
Docker version 17.05.0-ce, build 89658be

**Comment by santiagogil** [comment]
## Varios avances

* Estuve probando la implementación de secretos en swarm y va perfecto.
* Ya están publicadas en hub.docker.com las imágenes siep-php-fpm y siep-nginx en la organización decyt.
* Logré un workflow claro para desarrollo --> testeo --> implementación basado en docker-compose y docker stack. Manteniendo un único archivo .yml podemos correr la aplicación completa en desarrollo via docker-compose y en producción via docker stack.
* Inicié la instalación del nodo con swarm en el server.
* Utilizando la nueva sintaxis de docker-compose resulta trivial implementar un cluster memcached, lo cual implica un avance enorme para cerrar #13.
