### ISSUE TITLE
Optimizaciones vía Caches

### ISSUE THREAD

**Issue by gpabloandres** [decyt-tdf/siep#52]
[Ver Guía](https://doctorfox.wordpress.com/2013/08/20/better-performance-speeding-up-your-cakephp-website/) para: Cache Query Results, Install Memory Based Caching y Configure Nginx to use Memcached.

**Comment by santiagogil** [comment]
Para cerrar este issue son necesarios dos trabajos complementarios y correlativos:
1. [x] Implementar un cache desacoplado del proceso php que permita un escalado orizontal sin caer en *race conditions*.
2. [ ] Realizar las modificaciones pertinentes en el código para sacar el mayor provecho posible de dicho cache.
