### ISSUE TITLE
Listado de REPITENTES

### ISSUE THREAD

**Issue by gpabloandres** [decyt-tdf/siep#558]
## Comportamiento esperado
Desde el menú VER-->REPITENTES, visualizar/imprimir (bajo el mismo formato del listado de INSCRIPCIONES 2019) la nómina de REPITENTES según los filtros (institución, ciclo, año) indicados en el cuadro de BÚSQUEDA.

## Comportamiento actual
No se visualizan REPITENTES.

## Solución posible
Para la obtención de REPITENTES, se debe incorporar a la lógica de programación, revisar se repita el año de inscripción entre dos ciclos consecutivos.  

## Contexto
Listado requerido tanto desde las supervisiones técnicas como desde la unidad estadística.

# TAREAS PENDIENTES
- [ ] Boton para exportar resultados

**Comment by MaTiUs77** [comment]
Falta boton para exportacion a excel
