### ISSUE TITLE
Listado de Promocionados

### ISSUE THREAD

**Issue by gpabloandres** [decyt-tdf/siep#659]
## Comportamiento esperado
Desde el menú VER-->PROMOCIONADOS, visualizar/imprimir (bajo el mismo formato del listado de INSCRIPCIONES 2019) la nómina de PROMOCIONADOS según los filtros (institución, ciclo, año) indicados en el cuadro de BÚSQUEDA.

# TAREAS PENDIENTES
- [ ] Boton para exportar resultados

**Comment by MaTiUs77** [comment]
Falta boton para exportacion a excel
