### ISSUE TITLE
Réplicas db

### ISSUE THREAD

**Issue by santiagogil** [decyt-tdf/siep#8]
Implementar un esquema master slaves de base de datos que nos permita mantenes un master optimizado y exclusivo para escritura (innodb o percona) y una cantidad escalable (via swarm) de slaves optimizados para lectura.

(se habló también de migrar a postgres o percona, pero eso requiere una evaluación algo más profunda).

**Comment by santiagogil** [comment]
Existen dos imágenes, mysql bitnami y galera, que permiten implementar y escalar un cluster mysql con failover mediante docker-compose y variables de entorno.

@gpabloandres: qué tan complejo es apuntar las lecturas a los slave y las escrituras a los master desde cake?

Si podemos tener de antemano la implementación hecha y comentada en el código, estaríamos en condiciones de contar con redundancia y failover mysql desde el día cero.

**Comment by santiagogil** [comment]
## Muy buén material de referencia:

* https://www.percona.com/blog/2017/02/07/overview-of-different-mysql-replication-solutions/
* https://github.com/zalando/patroni/blob/master/README.rst

**Comment by santiagogil** [comment]
* http://blog.lwolf.org/post/how-to-deploy-ha-postgressql-cluster-on-kubernetes/

**Comment by gpabloandres** [comment]
Para convertir la BD de MySQL a PostgreSQL veo que una de las herramientas que utilizan es "SQL ARCHITEC".

**Comment by gpabloandres** [comment]
ó quizás usar algunos de estos scripts:
https://github.com/mihailShumilov/mysql2postgresql
https://github.com/philipsoutham/py-mysql2pgsql

**Comment by santiagogil** [comment]
Tranqui. Logré una migración exitosa utilizando la última versión de pgloader dockerizado.
Resultó muy práctico porque me permitió hacer el trabajo integramente en contenedores sin instalar nada en mi máquina.
Me demoré en el push porque la última versión de la base de datos introdujo algunas inconsistencias, que bién me marcó Matias.
Es decir, el esunto está resuelto pero demorado. En cuanto tenga un rato de teclado salimos con postgres.
En cuanto a replicación y redundancia, me atrevería a adelantar que vamos con patroni. Es una implementación consistente, liviana y lo suficientemente flexible para adaptarse a futuros desarrollos.

**Comment by santiagogil** [comment]
Depende del abandono del trabajo manual directo sobre la db.
