### ISSUE TITLE
Reglas de validación en modelos

### ISSUE THREAD

**Issue by pablodeleon** [decyt-tdf/siep#96]
*Verificar las reglas de validación en los modelos para evitar inestabilidad en la base de datos.

**Comment by gpabloandres** [comment]
Pablo: enriquecí un poquito más el uso de reglas de validaciones. Lo apliqué en el Modelo "Persona" por la diversidad de casos que allí existen. Habría que continuar sumando nuevas reglas y escalar al resto de los Modelos, e inclusive -Matias- aplicarlas a los formularios de búsqueda.
