### ISSUE TITLE
Verificar el input apellido del formulario add[Alumno]

### ISSUE THREAD

**Issue by pablodeleon** [decyt-tdf/siep#97]
*Dicho input permite ingresar Null (el sistema lo toma como "vacío"). [verificar las reglas de validación]

**Comment by gpabloandres** [comment]
Aquí tenemos 2 errores: Con el Autocomplete no se registran los nombres y no está especificada la regla de validación para que no se cargue un alumno sin nombre.

**Comment by MaTiUs77** [comment]
Deberia estar solucionado con el merge @ #111
